# Schema for the configuration files of the featurepolicy module.

featurepolicy.settings:
  type: config_object
  label: 'Feature Policy Settings'
  mapping:
    enforce:
      type: featurepolicy_policy
      label: 'Enforce Policy'

featurepolicy_policy:
  type: mapping
  label: 'Policy'
  mapping:
    enable:
      type: boolean
      label: 'Enable'
    directives:
      type: sequence
      label: 'Directives'
      sequence:
        type: featurepolicy_directive.[%key]

featurepolicy_directive_allow_list:
  type: mapping
  mapping:
    base:
      type: string
      label: 'Base'
    sources:
      type: sequence
      label: 'Sources'
      sequence:
        type: string

featurepolicy_directive.accelerometer:
  type: feature_policy_directive_allow_list
featurepolicy_directive.ambient-light-sensor:
  type: feature_policy_directive_allow_list
featurepolicy_directive.autoplay:
  type: feature_policy_directive_allow_list
featurepolicy_directive.battery:
  type: feature_policy_directive_allow_list
featurepolicy_directive.camera:
  type: feature_policy_directive_allow_list
featurepolicy_directive.display-capture:
  type: feature_policy_directive_allow_list
featurepolicy_directive.document-domain:
  type: feature_policy_directive_allow_list
featurepolicy_directive.encrypted-media:
  type: feature_policy_directive_allow_list
featurepolicy_directive.fullscreen:
  type: feature_policy_directive_allow_list
featurepolicy_directive.geolocation:
  type: featurepolicy_directive_allow_list
featurepolicy_directive.execution-while-not-rendered:
  type: feature_policy_directive_allow_list
featurepolicy_directive.execution-while-out-of-viewport:
  type: feature_policy_directive_allow_list
featurepolicy_directive.gyroscope:
  type: feature_policy_directive_allow_list
featurepolicy_directive.magnetometer:
  type: feature_policy_directive_allow_list
featurepolicy_directive.microphone:
  type: feature_policy_directive_allow_list
featurepolicy_directive.midi:
  type: feature_policy_directive_allow_list
featurepolicy_directive.navigation-override:
  type: feature_policy_directive_allow_list
featurepolicy_directive.payment:
  type: feature_policy_directive_allow_list
featurepolicy_directive.picture-in-picture:
  type: feature_policy_directive_allow_list
featurepolicy_directive.publickey-credentials:
  type: feature_policy_directive_allow_list
featurepolicy_directive.sync-xhr:
  type: feature_policy_directive_allow_list
featurepolicy_directive.usb:
  type: feature_policy_directive_allow_list
featurepolicy_directive.vr:
  type: feature_policy_directive_allow_list
featurepolicy_directive.wake-lock:
  type: feature_policy_directive_allow_list
featurepolicy_directive.xr-spatial-tracking:
  type: feature_policy_directive_allow_list
